### ISSUE TITLE
 TransportException file not found - packages are missing - NOT FIXED

### ISSUE THREAD

**Issue by socialnicheguru** [hiqdev/asset-packagist#108]
Please allow others to confirm before closing. This is not fixed. 
There are two issues: content mismatch which I do believe was fixed (and was not my issue in the first place).

The other is missing packages which is still going on. I am listing some examples I am receiving below. 

_Originally posted by @socialnicheguru in https://github.com/hiqdev/asset-packagist/issues/106#issuecomment-548350113_

**Comment by socialnicheguru** [comment]
Random packages are now not available. This is not the same issue as the content mismatch. 

How can this be soved. 

<img width="1273" alt="Screen Shot 2019-10-31 at 5 29 07 AM" src="https://user-images.githubusercontent.com/172735/67947005-dac18c00-fb9f-11e9-8bd0-c701227dfcd6.png">

**Comment by socialnicheguru** [comment]
This is another example:
https://github.com/hiqdev/asset-packagist/issues/106#issuecomment-548321626

**Comment by SilverFire** [comment]
There are around 600 packages, that are possibly out-of-sync. I've added them to an update queue, let's see whether your problem got fixed in 30 minutes

![image](https://user-images.githubusercontent.com/4499203/67950094-b55d6e00-fbf1-11e9-8230-bd1fa2a38ce2.png)

**Comment by fedfigca** [comment]
I'm still getting signature errors, 

`[Composer\Repository\RepositorySecurityException]                                                                       The contents of https://asset-packagist.org/p/npm-asset/is-integer/6b2910b9e76ac61efac57d3dc73a8f6cd7381428055d8218     dbc13e2a51654a72.json do not match its signature. This could indicate a man-in-the-middle attack or e.g. antivirus      software corrupting files. Try running composer again and report this if you think it is a mistake.`

**Comment by SilverFire** [comment]
I've added a [sanity checker](https://github.com/hiqdev/asset-packagist/commit/a6662e55e5dd1217458a5c376d63fba80c08073a) and I'm currently running it against all packages.

**Comment by SilverFire** [comment]
All the packages with wrong checksums were updated. Could you try again, please?

![Uploading image.png…]()

**Comment by fedfigca** [comment]
It worked fine for my setup 👍
Thanks a lot for your hard work.

**Comment by SilverFire** [comment]
@socialnicheguru do you think the issue can be closed now?

**Comment by jomonkj** [comment]
issue not resolved.

```ssh
  [Composer\Downloader\TransportException]                                                                                                                                                                
  The "https://asset-packagist.org/p/bower-asset/drmonty-datatables-plugins/9f2eb11601d9408660c80d23b2c3241bf7d07664eb94f7f0f2819e6b53a2263b.json" file could not be downloaded (HTTP/1.1 404 Not Found)  
                                                                                                                                                                                                        
```

**Comment by SilverFire** [comment]
It can be related to an outdated cache.
Could you try `composer clear-cache` and then `composer install` again?

**Comment by mv4** [comment]
> It can be related to an outdated cache.
> Could you try `composer clear-cache` and then `composer install` again?

![Screenshot from 2019-11-07 14-52-44](https://user-images.githubusercontent.com/3755838/68370170-72117b00-016e-11ea-8a90-fad22a97cdd2.png)

**Comment by FanGremlin** [comment]
have same problems
[Composer\Downloader\TransportException]
  Content-Length mismatch, received 81664 bytes out of the expected 4173071
this file not full load from composer
https://asset-packagist.org/p/provider-latest/7999bec2c879019853f636724c0f33fccf334d20c050d982774c645f54eae151.json

**Comment by hiqsol** [comment]
Is it ok now?

**Comment by FanGremlin** [comment]
yes, now is worked

**Comment by socialnicheguru** [comment]
It works for me too. 

It can be closed
