### ISSUE TITLE
https://cdn.asset-packagist.org/packages.js 403

### ISSUE THREAD

**Issue by sasha-** [hiqdev/asset-packagist#176]
There seem to be something going on with asset-packagist.org
 
https://asset-packagist.org/package/search?query=hello&platform=bower%2Cnpm

Search for any package returns database error:
Database Exception (#2002)
An internal server error occurred.

https://cdn.asset-packagist.org/packages.js  returns 403 

Additionally, requests from some Azure properties seem to be blocked - no response from 45.133.44.(1|2):443 at all.

**Comment by mbakals1** [comment]
Similar experience here. We are getting timeouts during builds (Azure DevOps) or browsers from our corporate network, but can load https://cdn.asset-packagist.org/packages.json fine from public internet. 

`The "https://cdn.asset-packagist.org/packages.json" file could not be downloaded: Failed to open stream: Connection timed out`

**Comment by SilverFire** [comment]
Hello!
I've contacted the CDN service provider and will you know as soon as they can get back to me.

**Comment by julien-langlois** [comment]
I feel like the problem is happening again today. 
I get a 403 error on the URL https://cdn.asset-packagist.org/packages.js.

**Comment by tonchik-tm-ya** [comment]
Problem again!

In CurlDownloader.php line 668:
The "https://cdn.asset-packagist.org/p/provider-latest/7fbdc91b4d5caa771ab80101361d66bd13080ea5b353feb72daecfe4cb8b1d05.json" file could not be downloaded (HTTP/2 404 )

**Comment by JPustkuchen** [comment]
@SilverFire any updates on this?

@tonchik-tm-ya see https://github.com/hiqdev/asset-packagist/issues/181 and https://github.com/hiqdev/asset-packagist/issues/180 there still seems to be major unresolved issues with the CDN.

**Comment by SilverFire** [comment]
[Fixed](https://github.com/hiqdev/asset-packagist/issues/181#issuecomment-3771979982) a race condition on Jan 20, should work better now

**Comment by ChinaskiJr** [comment]
Hello @SilverFire,
It seems that the issue is back. We have the same message on over 2 projects : 
```
curl error 28 while downloading https://cdn.asset-packagist.org/packages.js on: Operation timed out after 10003 milliseconds with 0 out of 0 bytes received"
```

Et when I try to go on https://cdn.asset-packagist.org/packages.js it returns a 403 error
