### ISSUE TITLE
Having trouble with gulp installation

### ISSUE THREAD

**Issue by jurgenhaas** [hiqdev/asset-packagist#21]
First of all, this is a great approach and I'm looking forward to getting all this included in my Drupal projects.

Currently I'm having trouble installing gulp and I saw the other issues here in the queue that I have to fetch missing packages on the web UI manually to get the missing dependencies resolved. I understand that I went through all that step by step. But I couldn't get it to work as I ended up with unresolvable dependencies. This is probably a misleading error from composer and what's really the case is probably just one more missing package that I couldn't find.

When I install gulp with NPM I end up with over 300 packages on the top level. But all the dependencies can be resolved.

My requirements are these:

```
    "npm-asset/gulp": "^3.9.1",
    "npm-asset/gulp-if": "^2.0.0",
    "npm-asset/gulp-notify": "^2.2.0",
    "npm-asset/gulp-sass": "^2.0.5",
    "npm-asset/gulp-sourcemaps": "^1.6.0",
    "npm-asset/minimist": "^1.2.0",
```

Any idea on how I could that sorted?

**Comment by SilverFire** [comment]
Hello, @jurgenhaas 
Thank you for you report.
You have a problem with installation because you requirements have dependencies on other packages that are not fetched on asset-packagist.org yet.
The best you can do for now is to run `composer update`, get the error that shows a missing package name and submit it manually to https://asset-packagist.org

I'm working on update for asset-packagist to fetch requirements recursively and submit missing packages automatically.

**Comment by jurgenhaas** [comment]
Thanks @SilverFire , that's exactly what i tried but as described in the op it's just not possible with the given complexity of the dependencies. Looks like i have to wait for the next phase then.

**Comment by SilverFire** [comment]
I will notify you on progress in this issue

**Comment by SilverFire** [comment]
I've implemented recursive packages' dependencies updating with the latest commits.
The server is currently processing all recursive dependencies and will finish work in 6-10 hours.

**Comment by jurgenhaas** [comment]
Wow, that was quick. I'll give it another try tomorrow then and let you know the results. Thanks @SilverFire

**Comment by jurgenhaas** [comment]
Unfortunately I still can't get it to work. To demonstrate the problem I've drilled down the composer.json file to the assets I want to add and in comparison I've created the equivalent package.json which is working with `npm install`

Maybe this example help to find out why it's failing?

[test.zip](https://github.com/hiqdev/asset-packagist/files/626728/test.zip)

**Comment by rob006** [comment]
Why are you trying to install gulp in this way? `asset-packagist` and `asset-plugin` was designed to provide frontend dependencies, using them to install regular npm tools will fail in most cases, since composer handle only flat dependencies structure. If you install gulp by npm you can find that some packages have nested `node_modules` directory, for example `readable-stream` is installed at leas two times in different versions: once in `node_modules`, second in `node_modules/glob-stream/node_modules`. You can't do this in composer, since it does not make any sense for PHP.

**Comment by SilverFire** [comment]
@rob006 glad to meet you here :) Thank you for your input.

@jurgenhaas Unfortunately, I can not install your set of requirements using `fxp/composer-asset-plugin`. We use that plugin, so we can not satisfy your installation request as well.
